version: "3"

services:
    mkdocs:
        container_name: mkdocs
        build:
            context: .
            dockerfile: Dockerfile
            target: prod
        restart: always
        ports:
            - "80:80"
